"""Named light-curve plotting configurations."""

# Add configurations here and register them below. Each must define xlim, ylim,
# multipliers, filt_freqs, band_colors, and band_secondary_colors.
lc_plot_settings_grb230812B = {
    "xlim": (1e4, 1e7),
    "ylim": (1e-9, 1e3),
    "multipliers": {
        "X-ray(10keV)": 10,
        "u": 0.25,
        "g": 0.5,
        "r": 1,
        "i": 5,
        "z": 20,
        "radio(90GHz)": 500,
        "radio(75GHz)": 300,
        "radio(15.5GHz)": 200,
        "radio(10GHz)": 100,
        "radio(6GHz)": 50,
        "radio(3GHz)": 25,
        "radio(1.3GHz)": 10,
    },
    "filt_freqs": {
        "i": 3.98913e14,
        "z": 3.46e14,
        "VT_B": 5.45077e14,
        "r": 4.8384e14,
        "J": 2.40161e14,
        "g": 6.249e14,
        "L": 5.55516e14,
        "u": 8.1178e14,
        "X-ray(10keV)": 2.41799e18,
        "radio(1.3GHz)": 1.3e9,
        "radio(3GHz)": 3e9,
        "radio(6GHz)": 6e9,
        "radio(10GHz)": 1e10,
        "radio(15GHz)": 1.5e10,
        "radio(15.5GHz)": 1.55e10,
        "radio(75GHz)": 7.5e10,
        "radio(90GHz)": 9e10,
    },
    "band_colors": {
        "X-ray(10keV)": "darkviolet",
        "u": "teal",
        "u'": "teal",
        "VT_B": "royalblue",
        "g": "darkgreen",
        "g'": "darkgreen",
        "r": "tab:red",
        "r'": "tab:red",
        "i": "darkgoldenrod",
        "i'": "darkgoldenrod",
        "z": "peru",
        "z'": "peru",
        "VT_R": "orange",
        "R": "magenta",
        "J": "olive",
        "radio(1.3GHz)": "darkgreen",
        "radio(3GHz)": "cornflowerblue",
        "radio(6GHz)": "peru",
        "radio(10GHz)": "#562778",
        "radio(15GHz)": "#441E5F",
        "radio(15.5GHz)": "deepskyblue",
        "radio(75GHz)": "olive",
        "radio(90GHz)": "#9141CA",
    },
    "band_secondary_colors": {
        "X-ray(10keV)": "lavender",
        "u": "mediumturquoise",
        "VT_B": "lightsteelblue",
        "g": "mediumaquamarine",
        "g'": "mediumaquamarine",
        "r": "lightcoral",
        "r'": "lightcoral",
        "i": "khaki",
        "i'": "khaki",
        "z": "peachpuff",
        "z'": "peachpuff",
        "VT_R": "peachpuff",
        "R": "plum",
        "J": "olive",
        "radio(1.3GHz)": "mediumaquamarine",
        "radio(3GHz)": "cornflowerblue",
        "radio(6GHz)": "peachpuff",
        "radio(10GHz)": "#5F3E77",
        "radio(15GHz)": "#4D385C",
        "radio(15.5GHz)": "lightblue",
        "radio(75GHz)": "tan",
        "radio(90GHz)": "#A97BCA",
    },
}
lc_plot_settings_default = {
    "xlim": (1e4, 3e6),
    "ylim": (1e-9, 1e5),
    "multipliers": {
        "X-ray(10keV)": 32,
        "u": 1,
        "g": 2,
        "VT_B": 4,
        "r": 8,
        "R": 16,
        "i": 32,
        "z'": 32,
        "VT_R": 64,
        "J": 128,
        "radio(15.5GHz)": 1024,
    },
    "filt_freqs": {
        "i": 3.98913e14,
        "z": 3.46e14,
        "VT_B": 5.45077e14,
        "r": 4.8384e14,
        "J": 2.40161e14,
        "g": 6.249e14,
        "L": 5.55516e14,
        "u": 8.1178e14,
        "X-ray(10keV)": 2.41799e18,
        "radio(1.3GHz)": 1.3e9,
        "radio(3GHz)": 3e9,
        "radio(6GHz)": 6e9,
        "radio(10GHz)": 1e10,
        "radio(15GHz)": 1.5e10,
        "radio(15.5GHz)": 1.55e10,
        "radio(75GHz)": 7.5e10,
        "radio(90GHz)": 9e10,
    },
    "band_colors": {
        "X-ray(10keV)": "darkviolet",
        "u": "teal",
        "u'": "teal",
        "VT_B": "royalblue",
        "g": "darkgreen",
        "g'": "darkgreen",
        "r": "tab:red",
        "r'": "tab:red",
        "i": "darkgoldenrod",
        "i'": "darkgoldenrod",
        "z": "peru",
        "z'": "peru",
        "VT_R": "orange",
        "R": "magenta",
        "J": "olive",
        "radio(1.3GHz)": "darkgreen",
        "radio(3GHz)": "cornflowerblue",
        "radio(6GHz)": "peru",
        "radio(10GHz)": "#562778",
        "radio(15GHz)": "#441E5F",
        "radio(15.5GHz)": "deepskyblue",
        "radio(75GHz)": "olive",
        "radio(90GHz)": "#9141CA",
    },
    "band_secondary_colors": {
        "X-ray(10keV)": "lavender",
        "u": "mediumturquoise",
        "VT_B": "lightsteelblue",
        "g": "mediumaquamarine",
        "g'": "mediumaquamarine",
        "r": "lightcoral",
        "r'": "lightcoral",
        "i": "khaki",
        "i'": "khaki",
        "z": "peachpuff",
        "z'": "peachpuff",
        "VT_R": "peachpuff",
        "R": "plum",
        "J": "olive",
        "radio(1.3GHz)": "mediumaquamarine",
        "radio(3GHz)": "cornflowerblue",
        "radio(6GHz)": "peachpuff",
        "radio(10GHz)": "#5F3E77",
        "radio(15GHz)": "#4D385C",
        "radio(15.5GHz)": "lightblue",
        "radio(75GHz)": "tan",
        "radio(90GHz)": "#A97BCA",
    },
}

lc_plot_settings_map = {
    "default": lc_plot_settings_default,
    "grb230812B": lc_plot_settings_grb230812B,
}
